language: go

go:
  - 1.6

install:
  - go get github.com/golang/lint/golint
  - go get github.com/chromium/hstspreload
  - go get cloud.google.com/go/datastore
  - go get google.golang.org/api/option
  - go get google.golang.org/grpc
  - make get-datastore-emulator

script:
  - make travis
